name: Run Test Python Script on Push

on:
  push:
    branches:
      - master  # Cambia esto si quieres otra rama

jobs:
  run-test:
    runs-on: ubuntu-latest  # Usa el sistema operativo Ubuntu

    steps:
      # Paso 1: Checkout del código
      - name: Checkout code
        uses: actions/checkout@v2

      # Paso 2: Configurar Python
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.8'

      # Paso 3: Instalar dependencias
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      # Paso 4: Ejecutar el script de Python
      - name: Run test.py
        run: |
          echo "Token length from env (debug): ${#GH_TOKEN}"
          python test.py

      # Paso 5: Crear Release y subir el modelo con softprops/action-gh-release
      - name: Create Release and Upload Model
        uses: softprops/action-gh-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}  # Usa el token de acceso personal (PAT) o github.token
        with:
          files: modelo.h5  # Asegúrate de que el archivo 'modelo.h5' está generado en tu directorio de trabajo
