name: Run Test Python Script on Push

on:
  push:
    branches:
      - master  # o la rama que desees

jobs:
  run-test:
    runs-on: ubuntu-latest  # Usa el sistema operativo Ubuntu

    steps:
    # Paso 1: Checkout del código
    - name: Checkout code
      uses: actions/checkout@v2

    # Paso 2: Configurar Python
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'  # O la versión de Python que estés utilizando

    # Paso 3: Instalar dependencias
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt  # Instalar las dependencias listadas en requirements.txt

    # Paso 4: Ejecutar el script test.py
    - name: Run test.py
      run: |
        python test.py  # Ejecuta tu archivo test.py
